Update mkinitcpio hooks and install files

diff --git a/scripts/mkinitcpio/initcpio/install/fbsplash b/scripts/mkinitcpio/initcpio/install/fbsplash
--- a/scripts/mkinitcpio/initcpio/install/fbsplash
+++ b/scripts/mkinitcpio/initcpio/install/fbsplash
@@ -1,98 +1,113 @@
 
 install() {
-    (
-        . /etc/conf.d/fbsplash
+	(
+		. /etc/conf.d/splash
 
-        add_binary /sbin/fbcondecor_helper
+		if /bin/mountpoint -q /lib/splash/cache; then
+			/bin/umount /lib/splash/cache
+		fi
 
-        # add some stuff maybe required by the helper
-        #add_device /dev/tty0 c 4 0
-        for dir in /lib/splash/proc /lib/splash/sys # /dev/fb /dev/misc /dev/vc
-        do
-            add_dir $dir
-        done
+		# Add the helper
+		add_binary /sbin/fbcondecor_helper
 
-        # add a minimal conf file to avoid kernel panic because of syntax
-        file=$( /usr/bin/mktemp )
-        for var in SPLASH_MESSAGE_INIT SPLASH_MODE_REQ SPLASH_THEME
-        do
-            eval value=\"\$$var\"
-            [ -n "$value" ] && echo $var="'$value'"
-        done > $file
-        add_file $file /etc/conf.d/fbsplash
+		# Add the daemon for early start
+		if [[ $SPLASH_DAEMON = early ]]; then
+			add_binary /sbin/fbsplashd.static
+		fi
 
-        # List file paths contained in given Fbsplash theme cfg file
-        _get_cfg_files() {
-            < "$1" /bin/sed -re '
-                # convert all whitespace into single blanks
-                s,[[:space:]]+, ,g ; t L1
-                :L1
-                # drop comments, grouping directives and blank lines
-                /^ *([#<]|$)/ d
-                # get a filepath or drop
-                s,.*[ =]([^ ]*/[^ ]+).*,\1, ; t ; d
-            ' | /usr/bin/sort -u
-        }
+		# Add a clean config file avoiding errors when running the hook
+		file=$( /usr/bin/mktemp )
+		for var in SPLASH_INIT_MESSAGE SPLASH_MODE_REQ SPLASH_THEME SPLASH_TTY \
+		           SPLASH_AUTOVERBOSE SPLASH_EFFECTS SPLASH_TEXTBOX
+		do
+			eval value=\"\$$var\"
+			[ -n "$value" ] && echo $var="'$value'"
+		done >|$file
+		add_file $file /etc/conf.d/splash
 
-        # Check if cfg file name or path
-        _match_cfg() {
-            [[ "$1" =~ (^|/)[0-9]+x[0-9]+\.cfg$ ]]
-        }
+		# List file paths contained in given Fbsplash theme cfg file
+		_get_cfg_files() {
+			< "$1" /bin/sed -re '
+				# convert all whitespace into single blanks
+				s,[[:space:]]+, ,g ; t L1
+				:L1
+				# drop comments, grouping directives and blank lines
+				/^ *([#<]|$)/ d
+				# get a filepath or drop
+				s,.*[ =]([^ ]*/[^ ]+).*,\1, ; t ; d
+			' | /usr/bin/sort -u
+		}
 
-    # Add non-cfg files in given dir
-        _add_non_cfg_files() {
-            local file dir="$1"
-            for file in $( /bin/ls "$dir" ); do
-                if [ -f "$dir/$file" ]; then
-                    _match_cfg "$file" || add_file "$dir/$file"
-                fi
-            done
-        }
+		# Check if cfg file name or path
+		_match_cfg() {
+			[[ "$1" =~ (^|/)[0-9]+x[0-9]+\.cfg$ ]]
+		}
 
-        # add global non-cfg files
-        _add_non_cfg_files /etc/splash
+		# Add non-cfg files in given dir
+		_add_non_cfg_files() {
+			local file dir="$1"
+			for file in $( /bin/ls "$dir" ); do
+				if [ -f "$dir/$file" ]; then
+					_match_cfg "$file" || add_file "$dir/$file"
+				fi
+			done
+		}
 
-        # add themes
-        for theme in ${SPLASH_THEMES[*]}; do # string list and array allowed
-            [ ${theme:0:1} = / ] || theme=/etc/splash/$theme
-            if _match_cfg $theme && \
-                add_file $theme
-            then
-                dir=$( dirname $theme )
-                # add non-cfg files in theme dir
-                _add_non_cfg_files $dir
-                # add files refered in cfg file by paths
-                for file in $( _get_cfg_files $theme ); do
-                    if [ ${file:0:1} = / ]; then
-                        add_file $file
-                        continue
-                    fi
-                    # path may be relative to theme-dir or to /etc/splash
-                    [ -e $dir/$file -o ! -f /etc/splash/$file ] && add_file $dir/$file
-                    [ -e /etc/splash/$file -o ! -f $dir/$file ] && add_file /etc/splash/$file
-                done
-            elif [ ! -d $theme ]; then
-                err "directory '${theme}' does not exist"
-            else
-                add_full_dir $theme
-            fi
-        done
+		# Add global non-cfg files
+		_add_non_cfg_files /etc/splash
 
-    # add default symlink if any
-        for symlink in /etc/splash/default
-        do
-            [ -L $symlink ] && add_symlink $symlink "$( readlink $symlink )"
-        done
-    )
+		# Add themes
+		dirs=""
+		for theme in ${SPLASH_THEMES[*]}; do # string list and array allowed
+			[ ${theme:0:1} = / ] || theme=/etc/splash/$theme
+			if [ -f $theme ]; then
+				if ! _match_cfg $theme; then
+					err "Not a valid theme cfg file name: $theme"
+					continue
+				fi
+				add_file $theme || continue
+				dir=$( dirname $theme )
+				# Add non-cfg files in theme dir
+				_add_non_cfg_files $dir
+				# Add files refered in cfg file by paths
+				for file in $( _get_cfg_files $theme ); do
+					if [ ${file:0:1} = / ]; then
+						add_file $file
+						continue
+					fi
+					# Path may be relative to theme-dir or to /etc/splash
+					[ -e $dir/$file -o ! -f /etc/splash/$file ] && add_file $dir/$file
+					[ -e /etc/splash/$file -o ! -f $dir/$file ] && add_file /etc/splash/$file
+				done
+			elif [ -d $theme ]; then
+				dir=$theme
+				add_full_dir $dir
+			else
+				err "Theme not found: $theme"
+				continue
+			fi
+			if [[ " "$dirs" " != *" "$dir" "* ]]; then
+				dirs+=" "$dir
+			fi
+		done
+		for dir in $dirs; do
+			# Add the rc_init-pre script if we have one
+			# Currently this just prevents early daemon start for the theme
+			if [[ $SPLASH_DAEMON = early && -x $dir/scripts/rc_init-pre ]]; then
+				add_file $dir/scripts/rc_init-pre || continue
+				echo "WARNING: rc_init-pre script found - no early daemon with '${dir##*/}'!" >&2
+			fi
+		done
+	)
 
-    SCRIPT="fbsplash"
+	SCRIPT="fbsplash"
 }
 
 help() {
 cat<<HELPEOF
-  This hook adds Fbsplash and themes specified in /etc/conf.d/fbsplash.
-  The hook script is responsible for starting Fbsplash if no fbcondecor
-  kernel patch is detected, so put this somewhere after udev.
+  This hook adds the FBconDecor helper and Fbsplash themes and maybe the
+  Fbsplash daemon as specified in /etc/conf.d/splash. Put it after udev
+  for early daemon start or when using a FBconDecor kernel.
 HELPEOF
 }
 
