rc.d update

diff --git a/scripts/profiles/archpwn-mini/overlay/etc/rc.d/functions b/scripts/profiles/archpwn-mini/overlay/etc/rc.d/functions
--- a/scripts/profiles/archpwn-mini/overlay/etc/rc.d/functions
+++ b/scripts/profiles/archpwn-mini/overlay/etc/rc.d/functions
@@ -4,17 +4,29 @@
 
 # width:
 
-STAT_COL=$(/bin/stty size)
-# strip the rows number, we just want columns
-STAT_COL=${STAT_COL##* }
-if [ "$STAT_COL" = "0" ]; then
-	# if output was 0 (serial console), set default width to 80
-	STAT_COL=80
-elif [ ! -t 1 ]; then
-	# disable color on output to non-tty
-	STAT_COL=80
-	USECOLOR=""
+STAT_COL=80
+if [ ! -t 1 ]; then
+  USECOLOR=""
+
+# stty will fail when stdin isn't a terminal
+elif [ -t 0 ]; then
+  STAT_COL="$(/bin/stty size)"
+  # stty gives "rows cols"; strip the rows number, we just want columns
+  STAT_COL="${STAT_COL##* }"
+
+else
+  # is /usr/share/terminfo already mounted, and TERM recognized?
+  /bin/tput cols &>/dev/null
+  if [ $? -eq 0 ]; then
+    STAT_COL=$(/bin/tput cols)
+  fi
 fi
+if [ "0$STAT_COL" -eq 0 ]; then
+  # if output was 0 (serial console), set default width to 80
+  STAT_COL=80
+  USECOLOR=""
+fi
+
 # we use 13 characters for our own stuff
 STAT_COL=$(($STAT_COL - 13))
 
@@ -60,6 +72,10 @@ if [ -t 1 ]; then
 	SAVE_POSITION="\033[s"
 	RESTORE_POSITION="\033[u"
 	DEL_TEXT="\033[$(($STAT_COL+4))G"
+else
+	SAVE_POSITION=""
+	RESTORE_POSITION=""
+	DEL_TEXT=""
 fi
 
 # prefixes:
@@ -74,7 +90,7 @@ deltext() {
 }
 
 printhl() {
-	printf "${C_OTHER}${PREFIX_HL} ${C_MAIN}${1}${C_CLEAR} \n"
+	printf "${C_OTHER}${PREFIX_HL} ${C_H1}${1}${C_CLEAR} \n"
 }
 
 printsep() {
@@ -84,30 +100,31 @@ printsep() {
 stat_bkgd() {
 	printf "${C_OTHER}${PREFIX_REG} ${C_MAIN}${1}${C_CLEAR} "
 	deltext
-	printf "   ${C_OTHER}[${C_BKGD}BKGD${C_OTHER}]${C_CLEAR} "
+	#printf "   ${C_OTHER}[${C_BKGD}BKGD${C_OTHER}]${C_CLEAR} "
+	printf "     ${C_BKGD}bg${C_CLEAR}   "
 }
 
 stat_busy() {
 	printf "${C_OTHER}${PREFIX_REG} ${C_MAIN}${1}${C_CLEAR} "
 	printf "${SAVE_POSITION}"
 	deltext
-	printf "   ${C_OTHER}[${C_BUSY}BUSY${C_OTHER}]${C_CLEAR} "
+	printf "     ${C_BUSY}..${C_CLEAR}   "
 }
 
 stat_append() {
 	printf "${RESTORE_POSITION}"
-	printf "${C_MAIN}${1}${C_CLEAR}"
+	printf -- "${C_MAIN}${1}${C_CLEAR}"
 	printf "${SAVE_POSITION}"
 }
 
 stat_done() {
 	deltext
-	printf "   ${C_OTHER}[${C_DONE}DONE${C_OTHER}]${C_CLEAR} \n"
+	printf "    ${C_DONE}done${C_CLEAR}  \n"
 }
 
 stat_fail() {
 	deltext
-	printf "   ${C_OTHER}[${C_FAIL}FAIL${C_OTHER}]${C_CLEAR} \n"
+	printf "    ${C_FAIL}fail${C_CLEAR}  \n"
 }
 
 stat_die() {
@@ -128,6 +145,24 @@ status() {
 		stat_fail
 		return 1
 	fi
+}
+
+#  usage : in_array( $needle, $haystack )
+# return : 0 - found
+#          1 - not found
+# Copied from makepkg
+in_array() {
+  local needle=$1; shift
+  [ -z "$1" ] && return 1 # Not Found
+  local item
+  for item in "$@"; do
+    local c="${item:0:1}"
+    if [ "x$c" = "x@" ]; then
+      item="${item:1}"
+    fi
+    [ "$item" = "$needle" ] && return 0 # Found
+  done
+  return 1 # Not Found
 }
 
 # daemons:
@@ -179,18 +214,96 @@ status_stopped() {
 }
 
 ck_status() {
-  if ck_daemon $1; then
+  ck_daemon $1
+  if [ $? -eq 1 ]; then
     status_started
   else
     status_stopped
   fi		
 }
 
+###############################
+# Custom hooks in initscripts #
+###############################
+# Hooks can be used to include custom code in various places in the rc.* scripts
+#
+# Define a hook function in a functions.d file using:
+#  function_name() {
+#    ...
+#  }
+#  add_hook hook_name function_name
+# It is allowed to register several hook functions for the same hook
+# Is is also allowed to register the same hook function for several hooks
+#
+# Currently, the following hooks exist:
+# sysinit_start: at the beginning of rc.sysinit
+# multi_start: at the beginning of rc.multi
+# single_start: at the beginning of rc.single
+# shutdown_start: at the beginning of rc.shutdown
+# sysinit_end: at the end of rc.sysinit
+# multi_end: at the end of rc.multi
+# single_end: at the end of rc.single
+# sysinit_udevlaunched: after udev has been launched in rc.sysinit
+# single_udevlaunched: after udev has been launched in rc.single
+# sysinit_udevsettled: after uevents have settled in rc.sysinit
+# single_udevsettled: after uevents have settled in rc.single
+# sysinit_premount: before local filesystems are mounted, but after root is mounted read-write in rc.sysinit
+# shutdown_prekillall: before all processes are being killed in rc.shutdown
+# single_prekillall: before all processes are being killed in rc.single
+# shutdown_postkillall: after all processes have been killed in rc.shutdown
+# single_postkillall: after all processes have been killed in rc.single
+# shutdown_poweroff: directly before powering off in rc.shutdown
+#
+# Make sure to never override the add_hook and run_hook functions via functions.d
 
-#Source additional functions at the end to allow overrides
+declare -A hook_funcs
+
+add_hook() {
+	[ -z "$1" -o -z "$2" ] && return 1
+	hook_funcs["$1"]="${hook_funcs["$1"]} $2"
+}
+
+run_hook() {
+	local func
+
+	[ -z "$1" ] && return 1
+	for func in ${hook_funcs["$1"]}; do
+		${func}
+	done
+}
+
+# Function for setting console font if required
+set_consolefont() {
+    if [ -n "$CONSOLEFONT" ]; then
+	stat_busy "Loading Console Font: $CONSOLEFONT"
+	#CONSOLEMAP in UTF-8 shouldn't be used
+	if [ -n "$CONSOLEMAP" ] && echo "$LOCALE" | /bin/grep -qi utf ; then
+		CONSOLEMAP=""
+	fi
+	for i in /dev/tty[0-9]*; do
+		if [ -n "$CONSOLEMAP" ]; then
+			/usr/bin/setfont -m $CONSOLEMAP $CONSOLEFONT -C ${i} >/dev/null 2>&1
+		else
+			/usr/bin/setfont $CONSOLEFONT -C ${i} >/dev/null 2>&1
+		fi
+	done
+	if [ $? -ne 0 ]; then
+		stat_fail
+	else
+		if [ -n "$CONSOLEMAP" ]; then
+			echo 'if [ "$CONSOLE" = "" -a "$TERM" = "linux" -a -t 1 ]; then printf "\033(K"; fi' >>/etc/profile.d/locale.sh
+		fi
+		stat_done
+	fi
+    fi
+}
+
+# Source additional functions at the end to allow overrides
 for f in /etc/rc.d/functions.d/*; do
-  [ -e $f ] && . $f
+  if [ -e $f ]; then
+    . $f
+  fi
 done
 
 # End of file
-# vim: set ts=2 noet:
+# vim: set ft=sh sw=2 ts=2 et:
